name: SOCIALLY CI
on: 
  push:
    branches: [master]
  pull_request: 
    branches: [master]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "actions/checkout"
         uses: actions/checkout@v1
      - name: Use Node js v 19
        uses: actions/setup-node@v1
        with:
          node-version: '19'
      -run: npm install
      -run: npm run build --prefix client 