name: SOCIALLY CI
on: 
  push:
    branches: [master]
  pull_request: 
    branches: [master]
  
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node js v 19
        uses: actions/setup-node@v2
        with:
          node-version: '19.6.0'
      -run: npm install
      -run: npm run build --prefix client 